function args = getMexLibArgs()
    % getMexLibArgs return arguments necessary to build Kafka utils

    % Copyright 2019, The MathWorks Inc.

    % Include folders
    % OLD
    %rdRoot = fullfile(getenv('PROGRAMFILES'), 'RdKafka');
    
    % NEW
    incDir = kafka.getRoot('app', 'sfun', 'inc');%    fullfile(rdRoot, 'include');
    libDir = kafka.getRoot('app', 'sfun', 'lib');% fullfile(rdRoot, 'system', 'blocks', 'lib');
    kDir = kafka.getRoot('..', 'CPP', 'librdkafka', 'src');
    jDir = kafka.getRoot('..', 'CPP', 'jansson', 'include');
    
    % Build on different systems
    if ismac
        error('This package has not been tested on OSX yet.\n');
    elseif isunix
        args = { ...
            ['-I"', incDir, '"'], ...
            ['-I"', kDir, '"'], ...
            ['-I"', jDir, '"'], ...
            ['-L"', libDir, '"'], ...
            ['-L"', kDir, '"'], ...
            '-R2018a',...
            '-lrdkafka', ...
            ...'-lrdkafka++', ...
            ...'-lz', ...
            '-lpthread', ...
            '-lrt', ...
            };
    elseif ispc
        % Win
        args = { ...
            ['-I"', incDir, '"'], ...
            ['-I"', kDir, '"'], ...
            ['-I"', jDir, '"'], ...
            ['-L"', libDir, '"'], ...
            '-R2018a',...
            '-lrdkafka.lib', ...
            ...'-lrdkafka++.lib', ...
            };
    else
        error('Unknown platform\n');
    end




end
