function args = getMexLibArgs()
    % getMexLibArgs return arguments necessary to build Kafka utils
    
    % Copyright 2019, The MathWorks Inc.
    
    if ismac
        error('This package has not been tested on OSX yet.\n');
    elseif isunix
        args = { ...
            '-lrdkafka', ...
            ...'-lrdkafka++', ...
            '-lz', ...
            '-lpthread', ...
            '-lrt', ...
            };
    elseif ispc
        % Win
        rdRoot = fullfile(getenv('PROGRAMFILES'), 'RdKafka');
        incDir = fullfile(rdRoot, 'include');
        libDir = fullfile(rdRoot, 'lib');
        args = { ...
            ['-I"', incDir, '"'], ...
            ['-L"', libDir, '"'], ...
            '-lrdkafka.lib', ...
            ...'-lrdkafka++.lib', ...
            };
    else
        error('Unknown platform\n');
    end
    
    
    
    
end
