function BASES = getBaseImageNames()
    % getBaseImages Returns the list of base images supported
    
    % Copyright 2019 The MathWorks, Inc.
    BASES = { ...
        'alpine:3.10.1', ...
        'ubuntu:18.04', ...
        'debian:stretch', ...
        };
end
    